### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by shaikhtariq11** [Devxhkl/RealtimeOCR#1]
Hi, 
First setting need to be done is :
Objective-C Bridging Header path should change.
After that Its crashing....
camera started well. while its detecting image crashed with the below error:(copying full console result)
"4
-0.649479
0.27098
(0.0,0.0)
4
-0.787679
0.85254
(0.0,0.0)
(0.0,0.0)
6
-0.75262
0.999432
4
-0.35365
0.607378
(0.0,0.0)
(0.0,0.0)
4
-0
0.0499376
6
-0.962206
0.058722
4
-0.262533
0.262926
5
-0.882971
-0.131438
6
-0.927877
0.322854
6
-0.925547
-0.066519
(86.0,22.0)
2015-03-27 14:33:06.146 OpenCVT[4803:2649466] BSXPCMessage received error for message: Connection interrupted
Empty page!!
Empty page!!
Recognized text: 
fatal error: unexpectedly found nil while unwrapping an Optional value "

I had put the proper image on focus which had clear text.

**Comment by markotect** [comment]
Thanks for letting me know,
I fixed the error.

With current parameters and filters that are applied, OpenCV should recognise  squares on a different color background (white square / black background) or with the frame of the square having a different color, like in the example (black frame / green background). So you might need to change the settings so that they suit your needs.

Also feel free to create a pull request for improvements.
